name: Build Android Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build Android Mod Packages
        run: |
          chmod +x gradlew
          ./gradlew deploy

      - name: Upload Mobile Mod Files
        uses: actions/upload-artifact@v4
        with:
          name: mindustry-android-mod
          path: |
            build/deploy/
            core/build/deploy/
